name: Update Kobo Calendar

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Check out the repository
      - uses: actions/checkout@v4

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: pip install icalendar requests pytz

      # 4️⃣ Generate calendar HTML
      - name: Generate calendar
        env:
          CALENDAR_ICS_URL: ${{ secrets.CALENDAR_ICS_URL }}
        run: python generate_calendar.py

      # 5️⃣ Deploy only calendar.html to gh-pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./  # only deploy calendar.html from root
          user_name: github-actions
          user_email: github-actions@github.com
          keep_files: false  # removes other files from gh-pages branch
          allow_empty_commit: true
