name: Update Calendar

on:
  schedule:
    # Runs every day at 00:05 UTC
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar pytz python-dateutil

      # Generate calendar HTML
      - name: Generate calendar
        run: python generate_calendar.py
        env:
          CALENDAR_ICS_URL: ${{ secrets.CALENDAR_ICS_URL }}

      # Commit updated calendar.html if changed
      - name: Commit updated calendar.html
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add calendar.html
          git diff --cached --quiet || git commit -m "Update calendar.html [skip ci]"
          
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./       # root directory (calendar.html is here)
          publish_branch: gh-pages
