name: Update Calendar

on:
  schedule:
    # Runs every day at 00:05 UTC
    - cron: '5 0 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar pytz

      # 4. Generate calendar HTML
      - name: Generate calendar
        run: python generate_calendar.py
        env:
          CALENDAR_ICS_URL: ${{ secrets.CALENDAR_ICS_URL }}

      # 5. Prepare deployment folder
      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp calendar.html deploy/

      # 6. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
