name: Update Calendar

on:
  schedule:
    # Runs every day at 00:05 UTC
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-calendar:
    runs-on: ubuntu-24.04

    steps:
      # Checkout repo with write access
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # needed for pushing

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests icalendar pytz

      # Generate calendar HTML
      - name: Generate calendar
        run: python generate_calendar.py
        env:
          CALENDAR_ICS_URL: ${{ secrets.CALENDAR_ICS_URL }}

      # Commit and push the updated calendar.html
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add calendar.html
          git diff-index --quiet HEAD || git commit -m "Update calendar.html [ci skip]"
          git push
